trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - infra/terraform/**
      - infra/scripts/**
      - .azure-pipelines/terraform.yml
      - .azure-pipelines/templates/**

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - infra/terraform/**

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: "1.7.5"
  TF_ROOT: "$(Build.SourcesDirectory)/infra/terraform/environments"
  AWS_SERVICE_CONNECTION: "aws-sistema-votaciones"
  AWS_REGION: "us-east-1"

stages:

  - stage: Bootstrap
    displayName: "Bootstrap Remote State"
    condition: ne(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: Bootstrap
        displayName: "S3 bucket + DynamoDB lock table"
        steps:
          - checkout: self
            fetchDepth: 1

          - task: AWSShellScript@1
            displayName: "Ejecutar bootstrap.sh"
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: filePath
              filePath: "infra/scripts/bootstrap.sh"

  - stage: Validate
    displayName: "Validate"
    dependsOn: []
    jobs:
      - job: ValidateDev
        displayName: "Validate DEV"
        steps:
          - template: templates/terraform-steps.yml
            parameters:
              environment: dev
              tfCommand: validate
              awsServiceConnection: $(AWS_SERVICE_CONNECTION)
              awsRegion: $(AWS_REGION)

  - stage: Plan
    displayName: "Plan DEV"
    dependsOn:
      - Bootstrap
      - Validate
    condition: and(succeeded('Validate'), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: PlanDev
        displayName: "terraform plan (dev)"
        steps:
          - template: templates/terraform-steps.yml
            parameters:
              environment: dev
              tfCommand: plan
              savePlan: true
              awsServiceConnection: $(AWS_SERVICE_CONNECTION)
              awsRegion: $(AWS_REGION)

  - stage: Apply
    displayName: "Apply DEV"
    dependsOn: Plan
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'dev'))
    jobs:
      - deployment: ApplyDev
        displayName: "terraform apply (dev)"
        environment: "dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/terraform-steps.yml
                  parameters:
                    environment: dev
                    tfCommand: apply
                    awsServiceConnection: $(AWS_SERVICE_CONNECTION)
                    awsRegion: $(AWS_REGION)
